// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// Code generated by mockery v1.0.0
package mocks

import apiclient "github.com/mendersoftware/go-lib-micro/apiclient"
import context "context"
import mock "github.com/stretchr/testify/mock"
import tenant "github.com/mendersoftware/useradm/client/tenant"

// ClientRunner is an autogenerated mock type for the ClientRunner type
type ClientRunner struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user, client
func (_m *ClientRunner) CreateUser(ctx context.Context, user *tenant.User, client apiclient.HttpRunner) error {
	ret := _m.Called(ctx, user, client)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.User, apiclient.HttpRunner) error); ok {
		r0 = rf(ctx, user, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTenant provides a mock function with given fields: ctx, username, client
func (_m *ClientRunner) GetTenant(ctx context.Context, username string, client apiclient.HttpRunner) (*tenant.Tenant, error) {
	ret := _m.Called(ctx, username, client)

	var r0 *tenant.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, string, apiclient.HttpRunner) *tenant.Tenant); ok {
		r0 = rf(ctx, username, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenant.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, apiclient.HttpRunner) error); ok {
		r1 = rf(ctx, username, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, tenantId, userId, u, client
func (_m *ClientRunner) UpdateUser(ctx context.Context, tenantId string, userId string, u *tenant.UserUpdate, client apiclient.HttpRunner) error {
	ret := _m.Called(ctx, tenantId, userId, u, client)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *tenant.UserUpdate, apiclient.HttpRunner) error); ok {
		r0 = rf(ctx, tenantId, userId, u, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
