FROM golang:1.11 as builder
# RUN apk update && apk upgrade && apk add xz-dev musl-dev gcc
RUN go get -u github.com/axw/gocov/gocov && go get -u golang.org/x/tools/cmd/cover && go get -u github.com/fzipp/gocyclo
RUN mkdir -p /go/src/github.com/mendersoftware/useradm
COPY . /go/src/github.com/mendersoftware/useradm
RUN cd /go/src/github.com/mendersoftware/useradm && \
    env CGO_ENABLED=0 go test -c -o useradm-test -coverpkg $(go list ./... | grep -v vendor | grep -v mock | grep -v test | tr  '\n' ,)

FROM alpine:3.4

EXPOSE 8080

COPY  --from=builder /go/src/github.com/mendersoftware/useradm/useradm-test /usr/bin/
COPY ./config.yaml /usr/bin/
STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/bin/useradm-test", "-test.coverprofile=/testing/coverage-acceptance.txt", "-acceptance-tests", "-test.run=TestRunMain", "-cli-args=--config=/usr/bin/config.yaml server --automigrate"]
