FROM golang:1.16.5-alpine3.12 as builder
RUN mkdir -p /go/src/github.com/mendersoftware/useradm
COPY . /go/src/github.com/mendersoftware/useradm
RUN cd /go/src/github.com/mendersoftware/useradm && \
    env CGO_ENABLED=0 go test -c -o useradm \
    -tags main -cover -covermode=atomic \
    -coverpkg $(go list ./... | grep -v vendor | grep -v mock | grep -v test | tr  '\n' ,)

FROM alpine:3.15.2

EXPOSE 8080
RUN mkdir -p /etc/useradm/rsa
ENTRYPOINT ["/usr/bin/useradm", "--config", "/etc/useradm/config.yaml"]
COPY ./config.yaml /etc/useradm/
COPY --from=builder /go/src/github.com/mendersoftware/useradm/useradm /usr/bin/

STOPSIGNAL SIGINT
