// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package main

import (
	"github.com/dgrijalva/jwt-go"
	"github.com/mendersoftware/go-lib-micro/log"
	"github.com/stretchr/testify/mock"
)

// MockJWTHandler is an autogenerated mock type for the JWTHandler type
type MockJWTHandler struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: subject
func (_m *MockJWTHandler) GenerateToken(subject string) (*jwt.Token, error) {
	ret := _m.Called(subject)

	var r0 *jwt.Token
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseLog provides a mock function with given fields: l
func (_m *MockJWTHandler) UseLog(l *log.Logger) {
	_m.Called(l)
}
